// Generated by CoffeeScript 1.10.0
module.exports = {
  parents: function(count) {
    var p;
    p = this.parent;
    while (count > 0) {
      if (p.parent) {
        p = p.parent;
      } else {
        break;
      }
      count--;
    }
    return p;
  }
};
