// Generated by CoffeeScript 1.10.0
module.exports = {
  parents: function(count) {
    var i, j, p, ref;
    p = this.parent;
    for (i = j = 0, ref = count; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      if (p.parent) {
        p = p.parent;
      } else {
        break;
      }
    }
    return p;
  }
};
